#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cd oversetMesh

./Allrun.pre

cd ../backgroundMesh

./Allrun.pre

# Serial
#runApplication $(getApplication)

# Parallel
runApplication decomposePar
runParallel  $(getApplication)

cd ..

#------------------------------------------------------------------------------
